plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/sessions/funny-admiring-ramanujan/mnt/dpg-leadgen"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]